###
GET http://localhost:8000/api/skills/
###
GET http://localhost:8000/api/skills/2
###
POST http://localhost:8000/api/skills HTTP/1.1
Content-Type: application/json

{
    "name": "Python"
}
###
PUT http://localhost:8000/api/skills/5 HTTP/1.1
Content-Type: application/json

{
    "name": "HTML"
}
###
DELETE http://localhost:8000/api/skills/5

###

